table _Measures
	lineageTag: f0dd64ff-3045-44fa-9aaa-b1c852f57601

	/// Total number of listings
	measure 'Total Listings' = COUNTROWS(Fact_Listings)
		formatString: #,0
		displayFolder: 📊 Volume
		lineageTag: 756bfda1-1c4c-4386-a71d-60b2d0120599

	/// Total number of unique hosts
	measure 'Total Hosts' = DISTINCTCOUNT(Fact_Listings[host_id])
		formatString: #,0
		displayFolder: 📊 Volume
		lineageTag: 82f4ed16-7816-45c3-959e-79d42850937d

	/// Average nightly price per listing
	measure 'Average Price' = AVERAGE(Fact_Listings[price])
		formatString: $#,0.00
		displayFolder: 💰 Pricing
		lineageTag: 7f8a7f41-b205-4ab8-bd2a-eb1b9a136b03

	/// Median nightly price per listing
	measure 'Median Price' = MEDIANX(Fact_Listings, Fact_Listings[price])
		formatString: $#,0.00
		displayFolder: 💰 Pricing
		lineageTag: e53dcf97-25ae-455e-b69d-454f2faf1d4a

	/// Estimated total revenue potential (price x availability days)
	measure 'Total Revenue Potential' = SUMX(Fact_Listings, Fact_Listings[price] * Fact_Listings[availability_365])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: 💰 Pricing
		lineageTag: 46be5c6d-d056-4580-8d07-e866fe7bd7db

	/// Average number of available days per year
	measure 'Average Availability (Days)' = AVERAGE(Fact_Listings[availability_365])
		formatString: #,0.0
		displayFolder: 📅 Availability & Booking
		lineageTag: 3fb2cc4d-83d3-4228-a35a-3d9c59ce2c8e

	/// Average minimum nights required per booking
	measure 'Average Minimum Nights' = AVERAGE(Fact_Listings[minimum_nights])
		formatString: #,0.0
		displayFolder: 📅 Availability & Booking
		lineageTag: 08d4b355-0435-4276-9087-b7674b00a7cd

	/// Total number of reviews across all listings
	measure 'Total Reviews' = SUM(Fact_Listings[number_of_reviews])
		formatString: #,0
		displayFolder: 📊 Volume
		lineageTag: 8bfd14c3-dd30-4d87-83ae-80aeecd04116

	/// Average number of reviews per listing
	measure 'Average Reviews per Listing' = AVERAGE(Fact_Listings[number_of_reviews])
		formatString: #,0.0
		displayFolder: ⭐ Reviews
		lineageTag: dfc7ce5d-1000-4c2f-95e3-43f78c52185a

	/// Average reviews received per month
	measure 'Average Reviews per Month' = AVERAGE(Fact_Listings[reviews_per_month])
		formatString: #,0.00
		displayFolder: ⭐ Reviews
		lineageTag: 058be70e-72cb-4f8b-b1c3-fd1edf5b0ea3

	/// Percentage of listings that have at least one review
	measure 'Listings with Reviews %' = DIVIDE(COUNTROWS(FILTER(Fact_Listings, Fact_Listings[number_of_reviews] > 0)), COUNTROWS(Fact_Listings))
		formatString: 0.0%
		displayFolder: ⭐ Reviews
		lineageTag: 97fb0b77-582f-40a5-b605-527246525588

	/// Listings available for 180 or more days per year
	measure 'High Availability Listings' = COUNTROWS(FILTER(Fact_Listings, Fact_Listings[availability_365] >= 180))
		formatString: #,0
		displayFolder: 📊 Volume
		lineageTag: 160cbcd7-dd03-4571-960f-5c3e1a9005cc

	/// Average number of listings per host
	measure 'Average Host Listings Count' = AVERAGE(Fact_Listings[calculated_host_listings_count])
		formatString: #,0.0
		displayFolder: 🏠 Hosts
		lineageTag: 30980c6b-acc3-4984-bfa8-1674715f2012

	/// Number of hosts with more than one listing
	measure 'Multi-Listing Hosts' = COUNTROWS(FILTER(VALUES(Fact_Listings[host_id]), CALCULATE(MAX(Fact_Listings[calculated_host_listings_count])) > 1))
		formatString: #,0
		displayFolder: 📊 Volume
		lineageTag: 2171f763-7b3d-4ec7-b1e7-942b01a0e825

	/// Average potential revenue per available day
	measure 'Price per Availability Day' = DIVIDE([Total Revenue Potential], SUMX(Fact_Listings, Fact_Listings[availability_365]))
		formatString: $#,0.00
		displayFolder: 💰 Pricing
		lineageTag: 49a00e70-ff3a-45c5-a1f1-31ebffcdc081

	/// Share of listings that are entire homes/apts
	measure '% Entire Home' = DIVIDE(CALCULATE([Total Listings], Dim_RoomType[room_type] = "Entire home/apt"), [Total Listings])
		formatString: 0.0%
		displayFolder: 📊 Volume
		lineageTag: 1df70eb6-9462-4d22-b8a4-36e95ba145f8

	/// Share of listings that are private rooms
	measure '% Private Room' = DIVIDE(CALCULATE([Total Listings], Dim_RoomType[room_type] = "Private room"), [Total Listings])
		formatString: 0.0%
		displayFolder: 📊 Volume
		lineageTag: bd5ac694-c5fd-4f22-869c-deb9c884c7de

	/// Average price for entire home/apt listings
	measure 'Avg Price - Entire Home' = CALCULATE([Average Price], Dim_RoomType[room_type] = "Entire home/apt")
		formatString: $#,0.00
		displayFolder: 💰 Pricing
		lineageTag: 3fb5a8a4-da39-4cbc-a09a-f4dca66da083

	/// Average price for private room listings
	measure 'Avg Price - Private Room' = CALCULATE([Average Price], Dim_RoomType[room_type] = "Private room")
		formatString: $#,0.00
		displayFolder: 💰 Pricing
		lineageTag: ff59b33d-5fe6-45b2-8d8d-abeaad9d2c9a

	/// Estimated occupancy rate proxy: (365 - avg availability) / 365
	measure 'Occupancy Rate Proxy' = DIVIDE(365 - [Average Availability (Days)], 365)
		formatString: 0.0%
		displayFolder: 📅 Availability & Booking
		lineageTag: d21b32f0-595c-4233-bd62-d777165d5efe

	/// Average revenue potential per listing
	measure 'Revenue Potential per Listing' = DIVIDE([Total Revenue Potential], [Total Listings])
		formatString: $#,0
		displayFolder: 💰 Pricing
		lineageTag: fec7e3f6-d021-4e07-88df-a36871dc8f17

	/// Neighbourhood with the most listings
	measure 'Top Neighbourhood by Listings' = TOPN(1, VALUES(Dim_Neighbourhood[neighbourhood]), CALCULATE([Total Listings]), DESC)
		displayFolder: 📊 Volume
		lineageTag: 411ae261-d22d-4db1-86a3-13e0f17ddd8c

	measure 'Total Listings per host' = DIVIDE([Total Listings], [Total Hosts], 0)
		displayFolder: 📊 Volume
		lineageTag: b7e5ad3f-08fd-4f4c-8135-cac7cfd9b9a1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Single-Listing Hosts' = [Total Hosts]-[Multi-Listing Hosts]
		formatString: 0
		displayFolder: 📊 Volume
		lineageTag: ee7111e6-0836-47ef-90ae-2f01aba17878

	measure 'Borough Deep Dive Title' = "Specific Information - " & SELECTEDVALUE(Dim_Neighbourhood[neighbourhood_group])
		lineageTag: 4ebe5cf3-2b44-489c-b10e-c1c44d19d115

	measure 'Specific Borough' = SELECTEDVALUE(Dim_Neighbourhood[neighbourhood_group])
		lineageTag: b7c4a586-38e9-4cc3-acac-787ba4174952

	measure 'Average Price No Filters' = CALCULATE([Average Price], REMOVEFILTERS())
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 0545b970-d874-4785-81d4-f18c361042e6

	measure 'Average Price Borough' =
			
			VAR Borough = SELECTEDVALUE(Dim_Neighbourhood[neighbourhood_group])
			RETURN
			CALCULATE(AVERAGE(Fact_Listings[price]), REMOVEFILTERS(), Dim_Neighbourhood[neighbourhood_group]=Borough)
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: caad4d06-0c00-4315-beb5-ed2bc512ec60

	measure 'Median Price No Filters' = CALCULATE([Median Price], REMOVEFILTERS())
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: e6168a6f-c3c0-466e-91ff-86a8b0446164

	measure 'Median Price Borough' = CALCULATE(MEDIAN(Fact_Listings[price]), REMOVEFILTERS(), Dim_Neighbourhood[neighbourhood_group]=SELECTEDVALUE(Dim_Neighbourhood[neighbourhood_group]))
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: c57e879c-c920-4380-a402-ac8e3b4572fc

	/// Average price across ALL listings, ignoring any page filters. Use as a global benchmark.
	measure 'Avg Price - All Listings' =
			CALCULATE(
			    AVERAGE(Fact_Listings[price]),
			    REMOVEFILTERS(Dim_Neighbourhood),
			    REMOVEFILTERS(Dim_RoomType),
			    REMOVEFILTERS(Fact_Listings)
			)
		formatString: $#,0.00
		displayFolder: 📊 Comparisons
		lineageTag: 912d8c85-b9b2-4613-8785-5a702b1f1311

	/// Average price for the borough of the currently selected neighbourhood, removing the neighbourhood filter while keeping the borough filter.
	measure 'Avg Price - Borough' =
			VAR SelectedBorough =
			    CALCULATE(
			        SELECTEDVALUE(Dim_Neighbourhood[neighbourhood_group]),
			        ALLEXCEPT(Dim_Neighbourhood, Dim_Neighbourhood[neighbourhood_group])
			    )
			RETURN
			    CALCULATE(
			        AVERAGE(Fact_Listings[price]),
			        REMOVEFILTERS(Dim_Neighbourhood),
			        Dim_Neighbourhood[neighbourhood_group] = SelectedBorough
			    )
		formatString: $#,0.00
		displayFolder: 📊 Comparisons
		lineageTag: 5aee5f86-e972-4b72-8c12-d859eb120a7e

	/// Price premium or discount of selected neighbourhood vs its borough average. Positive = pricier than borough.
	measure 'Avg Price - Neighbourhood vs Borough' = CALCULATE(AVERAGE(Fact_Listings[price])) - [Avg Price - Borough]
		formatString: $#,0.00
		displayFolder: 📊 Comparisons
		lineageTag: 1735a6b6-4e86-4b52-92e1-028a75131404

	/// Price premium or discount of selected neighbourhood vs overall NYC average. Positive = pricier than NYC.
	measure 'Avg Price - Neighbourhood vs All' = CALCULATE(AVERAGE(Fact_Listings[price])) - [Avg Price - All Listings]
		formatString: $#,0.00
		displayFolder: 📊 Comparisons
		lineageTag: a4137fb8-9091-4a34-bb9a-6d006814c5e6

	/// Percentage difference between this neighbourhood avg price and its borough average.
	measure 'Avg Price - Neighbourhood vs Borough %' =
			DIVIDE(
			    CALCULATE(AVERAGE(Fact_Listings[price])) - [Avg Price - Borough],
			    [Avg Price - Borough]
			)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 📊 Comparisons
		lineageTag: 2363cc5d-d647-4fd9-829e-a51834a12689

	/// Percentage difference between this neighbourhood avg price and the overall NYC average.
	measure 'Avg Price - Neighbourhood vs All %' =
			DIVIDE(
			    CALCULATE(AVERAGE(Fact_Listings[price])) - [Avg Price - All Listings],
			    [Avg Price - All Listings]
			)
		formatString: +0.0%;-0.0%;0.0%
		displayFolder: 📊 Comparisons
		lineageTag: 6d29e90f-ac0b-4073-88f2-45ed1a80b44c

	measure 'Specific Host' = SELECTEDVALUE(Dim_Host[host_name])
		lineageTag: 96e5dfd1-1143-42d5-9165-a54654912fd2

	measure 'Host Profile Map Title' = "Listings Locations - " & [Specific Host]
		lineageTag: 8a4ed9e6-06a3-4e49-a88d-e9fc427aeed9

	column Placeholder
		lineageTag: d358c859-40ca-43c5-ba21-ff8003b1e9dd
		isNameInferred
		sourceColumn: [Placeholder]

	partition _Measures = calculated
		mode: import
		source = ROW("Placeholder", BLANK())

