table _Measures
	lineageTag: f0dd64ff-3045-44fa-9aaa-b1c852f57601

	/// Total number of listings
	measure 'Total Listings' = COUNTROWS(Fact_Listings)
		formatString: #,0
		displayFolder: 📊 Volume

	/// Total number of unique hosts
	measure 'Total Hosts' = DISTINCTCOUNT(Fact_Listings[host_id])
		formatString: #,0
		displayFolder: 📊 Volume

	/// Average nightly price per listing
	measure 'Average Price' = AVERAGE(Fact_Listings[price])
		formatString: $#,0.00
		displayFolder: 💰 Pricing

	/// Median nightly price per listing
	measure 'Median Price' = MEDIANX(Fact_Listings, Fact_Listings[price])
		formatString: $#,0.00
		displayFolder: 💰 Pricing

	/// Estimated total revenue potential (price x availability days)
	measure 'Total Revenue Potential' = SUMX(Fact_Listings, Fact_Listings[price] * Fact_Listings[availability_365])
		formatString: $#,,,0,,"M"
		displayFolder: 💰 Pricing

	/// Average number of available days per year
	measure 'Average Availability (Days)' = AVERAGE(Fact_Listings[availability_365])
		formatString: #,0.0
		displayFolder: 📅 Availability & Booking

	/// Average minimum nights required per booking
	measure 'Average Minimum Nights' = AVERAGE(Fact_Listings[minimum_nights])
		formatString: #,0.0
		displayFolder: 📅 Availability & Booking

	/// Total number of reviews across all listings
	measure 'Total Reviews' = SUM(Fact_Listings[number_of_reviews])
		formatString: #,0
		displayFolder: 📊 Volume

	/// Average number of reviews per listing
	measure 'Average Reviews per Listing' = AVERAGE(Fact_Listings[number_of_reviews])
		formatString: #,0.0
		displayFolder: ⭐ Reviews

	/// Average reviews received per month
	measure 'Average Reviews per Month' = AVERAGE(Fact_Listings[reviews_per_month])
		formatString: #,0.00
		displayFolder: ⭐ Reviews

	/// Percentage of listings that have at least one review
	measure 'Listings with Reviews %' = DIVIDE(COUNTROWS(FILTER(Fact_Listings, Fact_Listings[number_of_reviews] > 0)), COUNTROWS(Fact_Listings))
		formatString: 0.0%
		displayFolder: ⭐ Reviews

	/// Listings available for 180 or more days per year
	measure 'High Availability Listings' = COUNTROWS(FILTER(Fact_Listings, Fact_Listings[availability_365] >= 180))
		formatString: #,0
		displayFolder: 📊 Volume

	/// Average number of listings per host
	measure 'Average Host Listings Count' = AVERAGE(Fact_Listings[calculated_host_listings_count])
		formatString: #,0.0
		displayFolder: 🏠 Hosts

	/// Number of hosts with more than one listing
	measure 'Multi-Listing Hosts' = COUNTROWS(FILTER(VALUES(Fact_Listings[host_id]), CALCULATE(MAX(Fact_Listings[calculated_host_listings_count])) > 1))
		formatString: #,0
		displayFolder: 📊 Volume

	/// Average potential revenue per available day
	measure 'Price per Availability Day' = DIVIDE([Total Revenue Potential], SUMX(Fact_Listings, Fact_Listings[availability_365]))
		formatString: $#,0.00
		displayFolder: 💰 Pricing

	/// Share of listings that are entire homes/apts
	measure '% Entire Home' = DIVIDE(CALCULATE([Total Listings], Dim_RoomType[room_type] = "Entire home/apt"), [Total Listings])
		formatString: 0.0%
		displayFolder: 📊 Volume

	/// Share of listings that are private rooms
	measure '% Private Room' = DIVIDE(CALCULATE([Total Listings], Dim_RoomType[room_type] = "Private room"), [Total Listings])
		formatString: 0.0%
		displayFolder: 📊 Volume

	/// Average price for entire home/apt listings
	measure 'Avg Price - Entire Home' = CALCULATE([Average Price], Dim_RoomType[room_type] = "Entire home/apt")
		formatString: $#,0.00
		displayFolder: 💰 Pricing

	/// Average price for private room listings
	measure 'Avg Price - Private Room' = CALCULATE([Average Price], Dim_RoomType[room_type] = "Private room")
		formatString: $#,0.00
		displayFolder: 💰 Pricing

	/// Estimated occupancy rate proxy: (365 - avg availability) / 365
	measure 'Occupancy Rate Proxy' = DIVIDE(365 - [Average Availability (Days)], 365)
		formatString: 0.0%
		displayFolder: 📅 Availability & Booking

	/// Average revenue potential per listing
	measure 'Revenue Potential per Listing' = DIVIDE([Total Revenue Potential], [Total Listings])
		formatString: $#,0
		displayFolder: 💰 Pricing

	/// Neighbourhood with the most listings
	measure 'Top Neighbourhood by Listings' = TOPN(1, VALUES(Dim_Neighbourhood[neighbourhood]), CALCULATE([Total Listings]), DESC)
		displayFolder: 📊 Volume

	column Placeholder
		lineageTag: d358c859-40ca-43c5-ba21-ff8003b1e9dd
		isNameInferred
		sourceColumn: [Placeholder]

	partition _Measures = calculated
		mode: import
		source = ROW("Placeholder", BLANK())

